---
title: "Caribbean COVID-19 TRACKER"
resource_files:
- google_analytics.html
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: row
    social: menu
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r global}
library(tidyverse)
library(readr)
library(plotly)
library(shinyWidgets)
library(shiny)
library(data.table)

includeHTML(("google_analytics.html")) #call to google analytics tracking script


####### custom ggplot theme ########

theme_jr<-function(){
  theme_minimal(base_size = 12, base_family = "Calibri")%+replace% 
    theme(
      plot.title = element_text(face = "bold", size=24, hjust = 0),
      plot.subtitle = element_text(size = 16, hjust = 0),
      plot.caption = element_text(hjust = 0),
      panel.grid = element_line(linetype = "dashed", colour = "grey92"),
      panel.grid.minor = element_blank()
    )
}


####### fecth data from JHU CCSE github #########

cases_data_url <-
  "https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
cases_data <- read.csv(url(cases_data_url))

death_data_url <-
  "https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
death_data <- read.csv(url(death_data_url))



recov_data_url <-
  "https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"
recov_data <- read.csv(url(recov_data_url))




#####reshape data to long format##########

cases_data <-
  cases_data %>% pivot_longer(
    -c(Province.State, Country.Region, Lat, Long),
    names_to = "date",
    values_to = "cases"
  )

death_data <-
  death_data %>% pivot_longer(
    -c(Province.State, Country.Region, Lat, Long),
    names_to = "date",
    values_to = "deaths"
  )




recov_data <-
  recov_data %>% pivot_longer(
    -c(Province.State, Country.Region, Lat, Long),
    names_to = "date",
    values_to = "recovs"
  )


covid_data <- cbind(cases_data, death_data$deaths)




####convert date variable from character to date#####

covid_data$date <-
  gsub("[^0-9.]", "", covid_data$date) #removes the X that prefixed teh date
covid_data$date <-
  gsub('\\.', '-', covid_data$date) #replace the ".", with a "-"
covid_data$date <-
  as.Date.character(covid_data$date, "%m-%d-%y") ##covert to date



recov_data$date <-
  gsub("[^0-9.]", "", recov_data$date) #removes the X that prefixed teh date
recov_data$date <-
  gsub('\\.', '-', recov_data$date) #replace the ".", with a "-"
recov_data$date <-
  as.Date.character(recov_data$date, "%m-%d-%y") ##covert to date



######filter for caribbean countries#######

carib <-
  c(
    "Cuba",
    "Dominican Republic",
    "Haiti",
    "Puerto Rico",
    "Jamaica",
    "Trinidad and Tobago",
    "Guyana",
    "Suriname",
    "Guadeloupe",
    "Martinique",
    "Bahamas",
    "Belize",
    "Barbados",
    "Saint Lucia",
    "Curacao",
    "Aruba",
    "Saint Vincent and the Grenadines",
    "British Virgin Islands",
    "Grenada",
    "Antigua and Barbuda",
    "Dominica",
    "Cayman Islands",
    "Saint Kitts and Nevis",
    "Sint Maarten",
    "Turks and Caicos Islands",
    "Anguilla",
    "Montserrat",
    "Saint Barthelemy",
    "Venezuela",
    "Bermuda"
  ) #list of caribbean countries

carib_data <-
  covid_data %>% filter(Country.Region %in% carib |
                          Province.State %in% carib) ######filter global data for caribbean countries using list
carib_data$Province.State <-
  as.character(carib_data$Province.State) #####convert factor to character
carib_data$Country.Region <-
  as.character(carib_data$Country.Region) ###### factor to character
carib_data$country <-
  if_else(
    carib_data$Province.State == "",
    carib_data$Country.Region,
    carib_data$Province.State
  )#create country variable combining country and province where applicable



recov_data <-
  recov_data %>% filter(Country.Region %in% carib |
                          Province.State %in% carib) #filter global data fro caribbean countries using list
recov_data$Province.State <-
  as.character(recov_data$Province.State) #convert factor to character
recov_data$Country.Region <-
  as.character(recov_data$Country.Region) #convert factor to character
recov_data$country <-
  if_else(
    recov_data$Province.State == "",
    recov_data$Country.Region,
    recov_data$Province.State
  )#create country variable combining country and province where applicable

recov_data<-recov_data%>%select(country, date, recovs)


carib_data<-left_join(carib_data, recov_data, by=c('country', 'date'))


colnames(carib_data)<-c("Province", "Region", "Lat", "Long", "Date", "Confirmed Cases", "Deaths", "Country", 
"Recoveries")

carib_data$Active<-carib_data$`Confirmed Cases`-(carib_data$Deaths+carib_data$Recoveries)


chart_data<-carib_data%>%filter(`Confirmed Cases`>0)%>%select(Country, Date,Recoveries,Active, Deaths )

chart_data<-chart_data%>%melt(id=1:2)

chart_colour<-c("Recoveries"="darkseagreen", "Active"="lightgoldenrod1","Deaths"="coral1")


today<-max(carib_data$Date)



```


TABLE
=====================================

Row {data-width=350}
-----------------------------------------------------------------------

### Confirmed Cases

```{r}

t_cases<-carib_data%>%filter(Date==today)%>%summarise(sum(`Confirmed Cases`))
valueBox(t_cases, color = "warning", icon ="fa-file-medical")

```


### Deaths

```{r}
t_deaths<-carib_data%>%filter(Date==today)%>%summarise(sum(Deaths))
valueBox(t_deaths, color = "danger" , icon ="fa-file-alt")

```

### Recoveries

```{r}
total_recov<-carib_data%>%filter(Date==today)%>%summarise(sum(Recoveries))
valueBox(total_recov, color = "success", icon ="fa-file-image")

```




Column {.sidebar}
-----------------------------------------------------------------------

Source data from John Hopkins University CSSE 2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository.

The tracker will be updated daily and is provided for informational purposes only.

Please send questions, queries or comments to sunrumdata@gmail.com



Row
-----------------------------------------------------------------------
```{r}

DT::datatable(carib_data%>%filter(Date==today)%>%select(Country, `Confirmed Cases`,Active, Deaths,Recoveries), colnames = c("Country", "Confirmed Cases","Active", "Deaths", "Recoveries"),rownames=FALSE, style = "bootstrap", options = list(
 columnDefs = list(list(className = 'dt-center', targets =0:4)), pageLength = 29))


```


COUNTRY TRENDS
=====================================


Column {.sidebar}
-----------------------------------------------------------------------


```{r}


```




```{r}
selectInput(
              "country",
              label = "Select Country:",
              choices = c(
                "Cuba",
                "Haiti",
                "Dominican Republic",
                "Jamaica",
                "Trinidad and Tobago",
                "Guyana",
                "Suriname",
                "Guadelope",
                "Martinique",
                "Bahamas",
                "Belize",
                "Barbados",
                "Saint Lucia",
                "Curacao",
                "Aruba",
                "Saint Vincent and the Grenadines",
                "British Virgin Islands",
                "Grenada",
                "Antigua and Barbuda",
                "Dominica",
                "Cayman Islands",
                "Saint Kitts and Nevis",
                "Sint Maarten",
                "Turks and Caicos Islands",
                "Anguilla",
                "Montserrat",
                "Saint Barthelemy",
                "Venezuela",
                "Bermuda"
              ),
  
              selected = "Antigua and Barbuda",
              )
```




Column
-----------------------------------------------------------------------

###  


```{r}


renderPlotly({


plot_data<-chart_data%>%filter(Country==input$country)



p4 <-
  ggplot() + geom_bar(
    data = plot_data,
    aes(
      x = Date,
      y = value,
      fill = factor(variable)
    ),
    stat = "identity",
    position = "stack"
  ) + scale_fill_manual(values = chart_colour) + 
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")+
  theme_minimal() + 
  labs(title = )+
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90),
    legend.title = element_blank(),
    axis.title.y = element_blank()
    
  
  )

ggplotly(p4)%>%layout(legend=list(x=0.3, orientation="h"))

})


```




